import {Contact} from './contact';

export const CONTACTS: Contact[] = [
 {
   id: 11,
   name: 'Mr. Nice',
   image: '../assets/1.jpg',
   isOnline: true,
   unReadCount: 0,
   lastMessage: {
     id: 1114,
     text: 'So how is the design challenge coming along bro? Made any progress so far?',
     date: '12:20 AM',
     isFirstMessageInGroup: true,
     isLastMessageInGroup: true,
     isSender: true,
     isOpened: true,
   },
   messages: [
     {
       id: 1111,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:00 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     },{
       id: 1112,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:05 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: false,
       isOpened: true,
     },{
       id: 1113,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:15 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: false,
       isOpened: true,
     },{
       id: 1114,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:20 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     }]
 },
 {
   id: 12,
   name: 'Narco',
   image: '../assets/2.jpg',
   isOnline: false,
   unReadCount: 2,
   lastMessage: {
     id: 1314,
     text: 'So how is the design challenge coming along bro? Made any progress so far?',
     date: '12:25 AM',
     isFirstMessageInGroup: true,
     isLastMessageInGroup: true,
     isSender: true,
     isOpened: true,
   },
   messages: [
     {
       id: 1211,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:00 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     },{
       id: 1212,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:05 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: false,
       isOpened: true,
     },{
       id: 1313,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:15 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: false,
       isOpened: true,
     },{
       id: 1314,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:25 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     }]
 },
 {
   id: 13,
   name: 'Bombasto',
   image: '../assets/3.jpg',
   isOnline: true,
   unReadCount: 0,
   lastMessage: {
     id: 1314,
     text: 'So how is the design challenge coming along bro? Made any progress so far?',
     date: '12:23 AM',
     isFirstMessageInGroup: true,
     isLastMessageInGroup: true,
     isSender: true,
     isOpened: true,
   },
   messages: [
     {
       id: 1311,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:00 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     },{
       id: 1312,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:05 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: false,
       isOpened: true,
     },{
       id: 1313,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:15 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: false,
       isOpened: true,
     },{
       id: 1314,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:23 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     }]
 },
 {
   id: 14,
   name: 'Celeritas',
   image: '../assets/4.jpg',
   isOnline: false,
   unReadCount: 0,
   lastMessage: {
     id: 1414,
     text: 'So how is the design challenge coming along bro? Made any progress so far?',
     date: '12:28 AM',
     isFirstMessageInGroup: true,
     isLastMessageInGroup: true,
     isSender: true,
     isOpened: true,
   },
   messages: [
     {
       id: 1411,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:00 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     },{
       id: 1412,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:05 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: false,
       isOpened: true,
     },{
       id: 1413,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:15 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: false,
       isOpened: true,
     },{
       id: 1414,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:28 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     }]
 },
 {
   id: 15,
   name: 'Magneta',
   image: '../assets/5.jpg',
   isOnline: true,
   unReadCount: 0,
   lastMessage: {
     id: 1514,
     text: 'So how is the design challenge coming along bro? Made any progress so far?',
     date: '12:30 AM',
     isFirstMessageInGroup: true,
     isLastMessageInGroup: true,
     isSender: true,
     isOpened: true,
   },
   messages: [
     {
       id: 1511,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:00 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     },{
       id: 1512,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:05 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: false,
       isOpened: true,
     },{
       id: 1513,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:15 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: false,
       isOpened: true,
     },{
       id: 1514,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:30 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     }]
 },
 {
   id: 16,
   name: 'RubberMan',
   image: '../assets/1.jpg',
   isOnline: true,
   unReadCount: 1,
   lastMessage: {
     id: 1614,
     text: 'So how is the design challenge coming along bro? Made any progress so far?',
     date: '12:14 AM',
     isFirstMessageInGroup: true,
     isLastMessageInGroup: true,
     isSender: true,
     isOpened: true,
   },
   messages: [
     {
       id: 1611,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:00 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     },{
       id: 1612,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:05 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: false,
       isOpened: true,
     },{
       id: 1613,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:15 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: false,
       isOpened: true,
     },{
       id: 1614,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:14 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     }]
 },
 {
   id: 17,
   name: 'Dynama',
   image: '../assets/2.jpg',
   isOnline: false,
   unReadCount: 0,
   lastMessage: {
     id: 1714,
     text: 'So how is the design challenge coming along bro? Made any progress so far?',
     date: '12:35 AM',
     isFirstMessageInGroup: true,
     isLastMessageInGroup: true,
     isSender: true,
     isOpened: true,
   },
   messages: [
     {
       id: 1711,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:00 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     },{
       id: 1712,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:05 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: false,
       isOpened: true,
     },{
       id: 1713,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:15 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: false,
       isOpened: true,
     },{
       id: 1714,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:35 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     }]
 },
 {
   id: 18,
   name: 'Dr IQ',
   image: '../assets/3.jpg',
   isOnline: false,
   unReadCount: 0,
   lastMessage: {
     id: 1814,
     text: 'So how is the design challenge coming along bro? Made any progress so far?',
     date: '12:20 AM',
     isFirstMessageInGroup: true,
     isLastMessageInGroup: true,
     isSender: true,
     isOpened: true,
   },
   messages: [
     {
       id: 1811,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:00 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     },{
       id: 1812,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:05 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: false,
       isOpened: true,
     },{
       id: 1813,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:15 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: false,
       isOpened: true,
     },{
       id: 1814,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:20 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     }]
 },
 {
   id: 19,
   name: 'Magma',
   image: '../assets/4.jpg',
   isOnline: true,
   unReadCount: 0,
   lastMessage: {
     id: 1914,
     text: 'So how is the design challenge coming along bro? Made any progress so far?',
     date: '12:13 AM',
     isFirstMessageInGroup: true,
     isLastMessageInGroup: true,
     isSender: true,
     isOpened: true,
   },
   messages: [
     {
       id: 1911,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:00 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     },{
       id: 1912,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:05 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: false,
       isOpened: true,
     },{
       id: 1913,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:15 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: false,
       isOpened: true,
     },{
       id: 1914,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:13 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     }]
 },
 {
   id: 20,
   name: 'Tornado',
   image: '../assets/5.jpg',
   isOnline: false,
   unReadCount: 2,
   lastMessage: {
     id: 2015,
     text: 'So how is the design challenge coming along bro? Made any progress so far?',
     date: '12:40 AM',
     isFirstMessageInGroup: false,
     isLastMessageInGroup: true,
     isSender: true,
     isOpened: true,
   },
   messages: [
     {
       id: 2011,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:00 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     },{
       id: 2012,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:05 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: false,
       isOpened: true,
     },{
       id: 2013,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:15 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: false,
       isOpened: true,
     },{
       id: 2014,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:40 AM',
       isFirstMessageInGroup: true,
       isLastMessageInGroup: false,
       isSender: true,
       isOpened: true,
     },{
       id: 2015,
       text: 'So how is the design challenge coming along bro? Made any progress so far?',
       date: '12:40 AM',
       isFirstMessageInGroup: false,
       isLastMessageInGroup: true,
       isSender: true,
       isOpened: true,
     }]
 }
]
